package main

// Code generated from the phase-1 capture. Do not edit by hand.
//
// observedEntityNames is the entity set the live graph held at mint time —
// what an operator writing a policy could actually enumerate.
// observedQueries and observedArgValues come from the phase-1 tools/call
// stream: the real argument values a real client sent.

import "encoding/json"

var observedEntityNames = []string{
	"AAT draft-01",
	"Ed25519",
	"JSON-RPC",
	"JWK",
	"JWS",
	"MCP",
	"PoP JWT",
	"RFC 7515",
	"RFC 8785",
	"audit record",
	"capability",
	"constraint",
	"delegation chain",
	"denial",
	"enforcement point",
	"internal/aat",
	"internal/audit",
	"internal/core",
	"internal/jcs",
	"internal/proxy",
	"latency budget",
	"permit",
	"proof of possession",
	"stdio transport",
	"tools/call",
	"trust anchor",
	"warden",
	"wardend",
}

var observedQueries = []string{
	"Ed25519",
	"JSON-RPC",
	"JWS",
	"audit",
	"capability",
	"delegation",
	"enforcement",
	"latency",
	"tools/call",
	"transport",
	"trust anchor",
}

// observedArgValues[tool] is every distinct value of that tool's one argument.
var observedArgValues = map[string][]json.RawMessage{
	"add_observations": {
		json.RawMessage(`[{"entityName":"Ed25519","contents":["Chosen over RSA for smaller key and signature sizes"]}]`),
		json.RawMessage(`[{"entityName":"JWK","contents":["Can represent an Ed25519 public key using the OKP key type"]},{"entityName":"PoP JWT","contents":["Short-lived, minted per-request to bind a call to the calling agent's key"]}]`),
		json.RawMessage(`[{"entityName":"JWS","contents":["Used by warden to encode signed AAT payloads for transport"]}]`),
		json.RawMessage(`[{"entityName":"audit record","contents":["Includes the full delegation chain snapshot at decision time for forensic replay"]}]`),
		json.RawMessage(`[{"entityName":"capability","contents":["Can be scoped down further at each delegation hop, never widened"]}]`),
		json.RawMessage(`[{"entityName":"denial","contents":["Always accompanied by a reason code surfaced back to the calling client"]},{"entityName":"permit","contents":["May attach a narrowed downstream capability if constraints require further scoping"]}]`),
		json.RawMessage(`[{"entityName":"internal/aat","contents":["Validates token expiry and signature chain before granting access"]}]`),
		json.RawMessage(`[{"entityName":"internal/proxy","contents":["Handles both stdio and HTTP transports for MCP traffic"]}]`),
		json.RawMessage(`[{"entityName":"latency budget","contents":["Typically targeted at low single-digit milliseconds of overhead per call"]},{"entityName":"RFC 7515","contents":["Published by the IETF JOSE working group"]}]`),
		json.RawMessage(`[{"entityName":"stdio transport","contents":["Default transport for local MCP server subprocesses spawned by the client"]},{"entityName":"tools/call","contents":["Carries the tool name and arguments that the enforcement point checks against capability scope"]}]`),
		json.RawMessage(`[{"entityName":"warden","contents":["Written in Go, targets deployment as a lightweight sidecar or standalone daemon"]}]`),
	},
	"create_entities": {
		json.RawMessage(`[{"name":"JSON-RPC","entityType":"protocol","observations":["Lightweight remote procedure call protocol using JSON","Version 2.0 is the transport format for MCP messages"]},{"name":"Ed25519","entityType":"algorithm","observations":["Elliptic curve signature algorithm used to sign AATs","Provides fast verification suitable for proxy enforcement points"]},{"name":"AAT draft-01","entityType":"specification","observations":["Draft specification defining the Agent Authorization Token format","Describes capability, constraint, and delegation chain structures"]},{"name":"capability","entityType":"concept","observations":["A grantable permission scoped to specific MCP tools or resources","Encoded within an AAT and checked at the enforcement point"]}]`),
		json.RawMessage(`[{"name":"JWS","entityType":"specification","observations":["JSON Web Signature format for signed payloads","Defined by RFC 7515"]},{"name":"JWK","entityType":"specification","observations":["JSON Web Key format for representing cryptographic keys as JSON"]},{"name":"RFC 8785","entityType":"specification","observations":["Defines the JSON Canonicalization Scheme (JCS)"]}]`),
		json.RawMessage(`[{"name":"RFC 7515","entityType":"specification","observations":["IETF standard defining JSON Web Signature (JWS)"]},{"name":"PoP JWT","entityType":"concept","observations":["Proof-of-Possession JWT, binds a token to a specific key held by the presenter"]},{"name":"stdio transport","entityType":"concept","observations":["Transport mechanism where MCP messages flow over standard input/output streams"]}]`),
		json.RawMessage(`[{"name":"constraint","entityType":"concept","observations":["A restriction narrowing when or how a capability may be exercised","Examples include time bounds, rate limits, and argument constraints"]},{"name":"delegation chain","entityType":"concept","observations":["An ordered sequence of delegations from a trust anchor down to the requesting agent","Each link must be verifiable against the previous signer's key"]},{"name":"proof of possession","entityType":"concept","observations":["Mechanism proving the holder of an AAT controls the associated private key","Prevents replay of a stolen token by a different holder"]},{"name":"audit record","entityType":"concept","observations":["Structured log entry capturing an authorization decision and its context","Written by internal/audit for compliance and forensic review"]}]`),
		json.RawMessage(`[{"name":"internal/proxy","entityType":"package","observations":["Implements the MCP proxy that intercepts JSON-RPC traffic","Acts as the enforcement point for authorization decisions"]},{"name":"internal/audit","entityType":"package","observations":["Produces audit records for every proxied MCP call","Persists tamper-evident logs of authorization decisions"]},{"name":"internal/jcs","entityType":"package","observations":["Implements JSON Canonicalization Scheme (RFC 8785)","Used to produce deterministic byte representations for signing and verification"]},{"name":"MCP","entityType":"protocol","observations":["Model Context Protocol, used for client-server tool invocation","Runs over JSON-RPC 2.0 messages"]}]`),
		json.RawMessage(`[{"name":"permit","entityType":"concept","observations":["The outcome when the enforcement point allows an MCP call to proceed"]},{"name":"latency budget","entityType":"concept","observations":["The maximum acceptable added latency the proxy may introduce per proxied call"]}]`),
		json.RawMessage(`[{"name":"scratch entity A","entityType":"temp","observations":["temporary placeholder for deletion exercise"]},{"name":"scratch entity B","entityType":"temp","observations":["temporary placeholder for deletion exercise"]}]`),
		json.RawMessage(`[{"name":"scratch-entity","entityType":"scratch","observations":["Temporary entity created only to demonstrate delete_entities"]}]`),
		json.RawMessage(`[{"name":"tools/call","entityType":"concept","observations":["The JSON-RPC method name used by MCP clients to invoke a tool on a server"]},{"name":"denial","entityType":"concept","observations":["The outcome when the enforcement point rejects an MCP call due to failed authorization checks"]}]`),
		json.RawMessage(`[{"name":"trust anchor","entityType":"concept","observations":["The root key or authority from which all delegation chains originate","Configured once and rarely rotated"]},{"name":"enforcement point","entityType":"concept","observations":["The component that evaluates an AAT and either allows or denies an MCP call","Implemented by internal/proxy at request time"]}]`),
		json.RawMessage(`[{"name":"warden","entityType":"project","observations":["Go project implementing an MCP authorization proxy","Sits between MCP clients and MCP servers to enforce authorization policy"]},{"name":"wardend","entityType":"binary","observations":["The daemon binary that runs the warden proxy service","Entry point that wires together internal/core, internal/proxy, internal/aat, internal/audit"]},{"name":"internal/core","entityType":"package","observations":["Core domain logic package for warden","Defines shared types like capability, constraint, delegation chain"]},{"name":"internal/aat","entityType":"package","observations":["Implements Agent Authorization Token (AAT) handling","Follows the AAT draft-01 specification"]}]`),
	},
	"create_relations": {
		json.RawMessage(`[{"from":"JWS","to":"RFC 7515","relationType":"defined_by"},{"from":"JWK","to":"Ed25519","relationType":"represents_key_for"},{"from":"RFC 8785","to":"internal/jcs","relationType":"specifies"}]`),
		json.RawMessage(`[{"from":"MCP","to":"JSON-RPC","relationType":"depends_on"},{"from":"internal/aat","to":"Ed25519","relationType":"depends_on"},{"from":"AAT draft-01","to":"capability","relationType":"cites"},{"from":"AAT draft-01","to":"constraint","relationType":"cites"},{"from":"AAT draft-01","to":"delegation chain","relationType":"cites"},{"from":"AAT draft-01","to":"proof of possession","relationType":"cites"}]`),
		json.RawMessage(`[{"from":"denial","to":"audit record","relationType":"generates"},{"from":"permit","to":"audit record","relationType":"generates"},{"from":"internal/proxy","to":"latency budget","relationType":"constrained_by"}]`),
		json.RawMessage(`[{"from":"enforcement point","to":"audit record","relationType":"enforces"},{"from":"internal/audit","to":"audit record","relationType":"implements"},{"from":"proof of possession","to":"Ed25519","relationType":"depends_on"},{"from":"capability","to":"constraint","relationType":"depends_on"},{"from":"internal/core","to":"capability","relationType":"contains"},{"from":"internal/core","to":"constraint","relationType":"contains"},{"from":"internal/core","to":"delegation chain","relationType":"contains"}]`),
		json.RawMessage(`[{"from":"enforcement point","to":"capability","relationType":"verifies"},{"from":"enforcement point","to":"constraint","relationType":"verifies"},{"from":"enforcement point","to":"delegation chain","relationType":"verifies"},{"from":"enforcement point","to":"proof of possession","relationType":"verifies"},{"from":"internal/proxy","to":"enforcement point","relationType":"implements"},{"from":"delegation chain","to":"trust anchor","relationType":"depends_on"}]`),
		json.RawMessage(`[{"from":"enforcement point","to":"tools/call","relationType":"authorizes"},{"from":"enforcement point","to":"denial","relationType":"produces"},{"from":"enforcement point","to":"permit","relationType":"produces"}]`),
		json.RawMessage(`[{"from":"internal/aat","to":"JWS","relationType":"uses"},{"from":"PoP JWT","to":"proof of possession","relationType":"implements"},{"from":"PoP JWT","to":"Ed25519","relationType":"depends_on"}]`),
		json.RawMessage(`[{"from":"internal/proxy","to":"internal/aat","relationType":"depends_on"},{"from":"internal/proxy","to":"internal/core","relationType":"depends_on"},{"from":"internal/proxy","to":"internal/audit","relationType":"depends_on"},{"from":"internal/aat","to":"internal/jcs","relationType":"depends_on"},{"from":"internal/aat","to":"AAT draft-01","relationType":"implements"},{"from":"internal/proxy","to":"MCP","relationType":"implements"}]`),
		json.RawMessage(`[{"from":"internal/proxy","to":"stdio transport","relationType":"implements"},{"from":"stdio transport","to":"MCP","relationType":"carries"},{"from":"tools/call","to":"MCP","relationType":"defined_by"}]`),
		json.RawMessage(`[{"from":"scratch entity A","to":"warden","relationType":"temp_relates_to"},{"from":"scratch entity B","to":"warden","relationType":"temp_relates_to"}]`),
		json.RawMessage(`[{"from":"warden","to":"internal/core","relationType":"contains"},{"from":"warden","to":"internal/aat","relationType":"contains"},{"from":"warden","to":"internal/proxy","relationType":"contains"},{"from":"warden","to":"internal/audit","relationType":"contains"},{"from":"warden","to":"internal/jcs","relationType":"contains"},{"from":"wardend","to":"warden","relationType":"depends_on"}]`),
	},
	"delete_entities": {
		json.RawMessage(`["scratch entity A"]`),
		json.RawMessage(`["scratch entity B"]`),
		json.RawMessage(`["scratch-entity"]`),
	},
	"delete_observations": {
		json.RawMessage(`[{"entityName":"Ed25519","observations":["Chosen over RSA for smaller key and signature sizes"]}]`),
		json.RawMessage(`[{"entityName":"JWK","observations":["Can represent an Ed25519 public key using the OKP key type"]}]`),
		json.RawMessage(`[{"entityName":"denial","observations":["Always accompanied by a reason code surfaced back to the calling client"]}]`),
		json.RawMessage(`[{"entityName":"latency budget","observations":["Typically targeted at low single-digit milliseconds of overhead per call"]}]`),
		json.RawMessage(`[{"entityName":"warden","observations":["Written in Go, targets deployment as a lightweight sidecar or standalone daemon"]}]`),
	},
	"delete_relations": {
		json.RawMessage(`[{"from":"capability","to":"constraint","relationType":"depends_on"}]`),
		json.RawMessage(`[{"from":"scratch entity A","to":"warden","relationType":"temp_relates_to"}]`),
		json.RawMessage(`[{"from":"scratch entity B","to":"warden","relationType":"temp_relates_to"}]`),
	},
	"open_nodes": {
		json.RawMessage(`["JWK","internal/jcs"]`),
		json.RawMessage(`["PoP JWT","proof of possession"]`),
		json.RawMessage(`["denial","permit","warden"]`),
		json.RawMessage(`["internal/aat","AAT draft-01"]`),
		json.RawMessage(`["internal/jcs","audit record"]`),
		json.RawMessage(`["latency budget","RFC 7515","RFC 8785"]`),
		json.RawMessage(`["proof of possession","trust anchor"]`),
		json.RawMessage(`["stdio transport","internal/proxy"]`),
		json.RawMessage(`["warden","wardend"]`),
	},
	"search_nodes": {
		json.RawMessage(`"Ed25519"`),
		json.RawMessage(`"JSON-RPC"`),
		json.RawMessage(`"JWS"`),
		json.RawMessage(`"audit"`),
		json.RawMessage(`"capability"`),
		json.RawMessage(`"delegation"`),
		json.RawMessage(`"enforcement"`),
		json.RawMessage(`"latency"`),
		json.RawMessage(`"tools/call"`),
		json.RawMessage(`"transport"`),
		json.RawMessage(`"trust anchor"`),
	},
}

// observedElems is the distinct *elements* of every array-valued argument the
// phase-1 client sent. subset over these is the finest thing Table 2 can say
// about an array of objects: it constrains each element, so it still permits
// recombinations the recording never contained.
var observedElems = map[string][]json.RawMessage{
	"add_observations": {
		json.RawMessage(`{"entityName":"Ed25519","contents":["Chosen over RSA for smaller key and signature sizes"]}`),
		json.RawMessage(`{"entityName":"JWK","contents":["Can represent an Ed25519 public key using the OKP key type"]}`),
		json.RawMessage(`{"entityName":"JWS","contents":["Used by warden to encode signed AAT payloads for transport"]}`),
		json.RawMessage(`{"entityName":"PoP JWT","contents":["Short-lived, minted per-request to bind a call to the calling agent's key"]}`),
		json.RawMessage(`{"entityName":"RFC 7515","contents":["Published by the IETF JOSE working group"]}`),
		json.RawMessage(`{"entityName":"audit record","contents":["Includes the full delegation chain snapshot at decision time for forensic replay"]}`),
		json.RawMessage(`{"entityName":"capability","contents":["Can be scoped down further at each delegation hop, never widened"]}`),
		json.RawMessage(`{"entityName":"denial","contents":["Always accompanied by a reason code surfaced back to the calling client"]}`),
		json.RawMessage(`{"entityName":"internal/aat","contents":["Validates token expiry and signature chain before granting access"]}`),
		json.RawMessage(`{"entityName":"internal/proxy","contents":["Handles both stdio and HTTP transports for MCP traffic"]}`),
		json.RawMessage(`{"entityName":"latency budget","contents":["Typically targeted at low single-digit milliseconds of overhead per call"]}`),
		json.RawMessage(`{"entityName":"permit","contents":["May attach a narrowed downstream capability if constraints require further scoping"]}`),
		json.RawMessage(`{"entityName":"stdio transport","contents":["Default transport for local MCP server subprocesses spawned by the client"]}`),
		json.RawMessage(`{"entityName":"tools/call","contents":["Carries the tool name and arguments that the enforcement point checks against capability scope"]}`),
		json.RawMessage(`{"entityName":"warden","contents":["Written in Go, targets deployment as a lightweight sidecar or standalone daemon"]}`),
	},
	"create_entities": {
		json.RawMessage(`{"name":"AAT draft-01","entityType":"specification","observations":["Draft specification defining the Agent Authorization Token format","Describes capability, constraint, and delegation chain structures"]}`),
		json.RawMessage(`{"name":"Ed25519","entityType":"algorithm","observations":["Elliptic curve signature algorithm used to sign AATs","Provides fast verification suitable for proxy enforcement points"]}`),
		json.RawMessage(`{"name":"JSON-RPC","entityType":"protocol","observations":["Lightweight remote procedure call protocol using JSON","Version 2.0 is the transport format for MCP messages"]}`),
		json.RawMessage(`{"name":"JWK","entityType":"specification","observations":["JSON Web Key format for representing cryptographic keys as JSON"]}`),
		json.RawMessage(`{"name":"JWS","entityType":"specification","observations":["JSON Web Signature format for signed payloads","Defined by RFC 7515"]}`),
		json.RawMessage(`{"name":"MCP","entityType":"protocol","observations":["Model Context Protocol, used for client-server tool invocation","Runs over JSON-RPC 2.0 messages"]}`),
		json.RawMessage(`{"name":"PoP JWT","entityType":"concept","observations":["Proof-of-Possession JWT, binds a token to a specific key held by the presenter"]}`),
		json.RawMessage(`{"name":"RFC 7515","entityType":"specification","observations":["IETF standard defining JSON Web Signature (JWS)"]}`),
		json.RawMessage(`{"name":"RFC 8785","entityType":"specification","observations":["Defines the JSON Canonicalization Scheme (JCS)"]}`),
		json.RawMessage(`{"name":"audit record","entityType":"concept","observations":["Structured log entry capturing an authorization decision and its context","Written by internal/audit for compliance and forensic review"]}`),
		json.RawMessage(`{"name":"capability","entityType":"concept","observations":["A grantable permission scoped to specific MCP tools or resources","Encoded within an AAT and checked at the enforcement point"]}`),
		json.RawMessage(`{"name":"constraint","entityType":"concept","observations":["A restriction narrowing when or how a capability may be exercised","Examples include time bounds, rate limits, and argument constraints"]}`),
		json.RawMessage(`{"name":"delegation chain","entityType":"concept","observations":["An ordered sequence of delegations from a trust anchor down to the requesting agent","Each link must be verifiable against the previous signer's key"]}`),
		json.RawMessage(`{"name":"denial","entityType":"concept","observations":["The outcome when the enforcement point rejects an MCP call due to failed authorization checks"]}`),
		json.RawMessage(`{"name":"enforcement point","entityType":"concept","observations":["The component that evaluates an AAT and either allows or denies an MCP call","Implemented by internal/proxy at request time"]}`),
		json.RawMessage(`{"name":"internal/aat","entityType":"package","observations":["Implements Agent Authorization Token (AAT) handling","Follows the AAT draft-01 specification"]}`),
		json.RawMessage(`{"name":"internal/audit","entityType":"package","observations":["Produces audit records for every proxied MCP call","Persists tamper-evident logs of authorization decisions"]}`),
		json.RawMessage(`{"name":"internal/core","entityType":"package","observations":["Core domain logic package for warden","Defines shared types like capability, constraint, delegation chain"]}`),
		json.RawMessage(`{"name":"internal/jcs","entityType":"package","observations":["Implements JSON Canonicalization Scheme (RFC 8785)","Used to produce deterministic byte representations for signing and verification"]}`),
		json.RawMessage(`{"name":"internal/proxy","entityType":"package","observations":["Implements the MCP proxy that intercepts JSON-RPC traffic","Acts as the enforcement point for authorization decisions"]}`),
		json.RawMessage(`{"name":"latency budget","entityType":"concept","observations":["The maximum acceptable added latency the proxy may introduce per proxied call"]}`),
		json.RawMessage(`{"name":"permit","entityType":"concept","observations":["The outcome when the enforcement point allows an MCP call to proceed"]}`),
		json.RawMessage(`{"name":"proof of possession","entityType":"concept","observations":["Mechanism proving the holder of an AAT controls the associated private key","Prevents replay of a stolen token by a different holder"]}`),
		json.RawMessage(`{"name":"scratch entity A","entityType":"temp","observations":["temporary placeholder for deletion exercise"]}`),
		json.RawMessage(`{"name":"scratch entity B","entityType":"temp","observations":["temporary placeholder for deletion exercise"]}`),
		json.RawMessage(`{"name":"scratch-entity","entityType":"scratch","observations":["Temporary entity created only to demonstrate delete_entities"]}`),
		json.RawMessage(`{"name":"stdio transport","entityType":"concept","observations":["Transport mechanism where MCP messages flow over standard input/output streams"]}`),
		json.RawMessage(`{"name":"tools/call","entityType":"concept","observations":["The JSON-RPC method name used by MCP clients to invoke a tool on a server"]}`),
		json.RawMessage(`{"name":"trust anchor","entityType":"concept","observations":["The root key or authority from which all delegation chains originate","Configured once and rarely rotated"]}`),
		json.RawMessage(`{"name":"warden","entityType":"project","observations":["Go project implementing an MCP authorization proxy","Sits between MCP clients and MCP servers to enforce authorization policy"]}`),
		json.RawMessage(`{"name":"wardend","entityType":"binary","observations":["The daemon binary that runs the warden proxy service","Entry point that wires together internal/core, internal/proxy, internal/aat, internal/audit"]}`),
	},
	"create_relations": {
		json.RawMessage(`{"from":"AAT draft-01","to":"capability","relationType":"cites"}`),
		json.RawMessage(`{"from":"AAT draft-01","to":"constraint","relationType":"cites"}`),
		json.RawMessage(`{"from":"AAT draft-01","to":"delegation chain","relationType":"cites"}`),
		json.RawMessage(`{"from":"AAT draft-01","to":"proof of possession","relationType":"cites"}`),
		json.RawMessage(`{"from":"JWK","to":"Ed25519","relationType":"represents_key_for"}`),
		json.RawMessage(`{"from":"JWS","to":"RFC 7515","relationType":"defined_by"}`),
		json.RawMessage(`{"from":"MCP","to":"JSON-RPC","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"PoP JWT","to":"Ed25519","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"PoP JWT","to":"proof of possession","relationType":"implements"}`),
		json.RawMessage(`{"from":"RFC 8785","to":"internal/jcs","relationType":"specifies"}`),
		json.RawMessage(`{"from":"capability","to":"constraint","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"delegation chain","to":"trust anchor","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"denial","to":"audit record","relationType":"generates"}`),
		json.RawMessage(`{"from":"enforcement point","to":"audit record","relationType":"enforces"}`),
		json.RawMessage(`{"from":"enforcement point","to":"capability","relationType":"verifies"}`),
		json.RawMessage(`{"from":"enforcement point","to":"constraint","relationType":"verifies"}`),
		json.RawMessage(`{"from":"enforcement point","to":"delegation chain","relationType":"verifies"}`),
		json.RawMessage(`{"from":"enforcement point","to":"denial","relationType":"produces"}`),
		json.RawMessage(`{"from":"enforcement point","to":"permit","relationType":"produces"}`),
		json.RawMessage(`{"from":"enforcement point","to":"proof of possession","relationType":"verifies"}`),
		json.RawMessage(`{"from":"enforcement point","to":"tools/call","relationType":"authorizes"}`),
		json.RawMessage(`{"from":"internal/aat","to":"AAT draft-01","relationType":"implements"}`),
		json.RawMessage(`{"from":"internal/aat","to":"Ed25519","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"internal/aat","to":"JWS","relationType":"uses"}`),
		json.RawMessage(`{"from":"internal/aat","to":"internal/jcs","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"internal/audit","to":"audit record","relationType":"implements"}`),
		json.RawMessage(`{"from":"internal/core","to":"capability","relationType":"contains"}`),
		json.RawMessage(`{"from":"internal/core","to":"constraint","relationType":"contains"}`),
		json.RawMessage(`{"from":"internal/core","to":"delegation chain","relationType":"contains"}`),
		json.RawMessage(`{"from":"internal/proxy","to":"MCP","relationType":"implements"}`),
		json.RawMessage(`{"from":"internal/proxy","to":"enforcement point","relationType":"implements"}`),
		json.RawMessage(`{"from":"internal/proxy","to":"internal/aat","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"internal/proxy","to":"internal/audit","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"internal/proxy","to":"internal/core","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"internal/proxy","to":"latency budget","relationType":"constrained_by"}`),
		json.RawMessage(`{"from":"internal/proxy","to":"stdio transport","relationType":"implements"}`),
		json.RawMessage(`{"from":"permit","to":"audit record","relationType":"generates"}`),
		json.RawMessage(`{"from":"proof of possession","to":"Ed25519","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"scratch entity A","to":"warden","relationType":"temp_relates_to"}`),
		json.RawMessage(`{"from":"scratch entity B","to":"warden","relationType":"temp_relates_to"}`),
		json.RawMessage(`{"from":"stdio transport","to":"MCP","relationType":"carries"}`),
		json.RawMessage(`{"from":"tools/call","to":"MCP","relationType":"defined_by"}`),
		json.RawMessage(`{"from":"warden","to":"internal/aat","relationType":"contains"}`),
		json.RawMessage(`{"from":"warden","to":"internal/audit","relationType":"contains"}`),
		json.RawMessage(`{"from":"warden","to":"internal/core","relationType":"contains"}`),
		json.RawMessage(`{"from":"warden","to":"internal/jcs","relationType":"contains"}`),
		json.RawMessage(`{"from":"warden","to":"internal/proxy","relationType":"contains"}`),
		json.RawMessage(`{"from":"wardend","to":"warden","relationType":"depends_on"}`),
	},
	"delete_entities": {
		json.RawMessage(`"scratch entity A"`),
		json.RawMessage(`"scratch entity B"`),
		json.RawMessage(`"scratch-entity"`),
	},
	"delete_observations": {
		json.RawMessage(`{"entityName":"Ed25519","observations":["Chosen over RSA for smaller key and signature sizes"]}`),
		json.RawMessage(`{"entityName":"JWK","observations":["Can represent an Ed25519 public key using the OKP key type"]}`),
		json.RawMessage(`{"entityName":"denial","observations":["Always accompanied by a reason code surfaced back to the calling client"]}`),
		json.RawMessage(`{"entityName":"latency budget","observations":["Typically targeted at low single-digit milliseconds of overhead per call"]}`),
		json.RawMessage(`{"entityName":"warden","observations":["Written in Go, targets deployment as a lightweight sidecar or standalone daemon"]}`),
	},
	"delete_relations": {
		json.RawMessage(`{"from":"capability","to":"constraint","relationType":"depends_on"}`),
		json.RawMessage(`{"from":"scratch entity A","to":"warden","relationType":"temp_relates_to"}`),
		json.RawMessage(`{"from":"scratch entity B","to":"warden","relationType":"temp_relates_to"}`),
	},
	"open_nodes": {
		json.RawMessage(`"AAT draft-01"`),
		json.RawMessage(`"JWK"`),
		json.RawMessage(`"PoP JWT"`),
		json.RawMessage(`"RFC 7515"`),
		json.RawMessage(`"RFC 8785"`),
		json.RawMessage(`"audit record"`),
		json.RawMessage(`"denial"`),
		json.RawMessage(`"internal/aat"`),
		json.RawMessage(`"internal/jcs"`),
		json.RawMessage(`"internal/proxy"`),
		json.RawMessage(`"latency budget"`),
		json.RawMessage(`"permit"`),
		json.RawMessage(`"proof of possession"`),
		json.RawMessage(`"stdio transport"`),
		json.RawMessage(`"trust anchor"`),
		json.RawMessage(`"warden"`),
		json.RawMessage(`"wardend"`),
	},
}
