// Command interop compares warden's §4.5 subsumption verdicts against tenuo's,
// on a corpus weighted toward the readings that require interpretation.
//
// This is a MEASUREMENT, not a test. Disagreements are the finding; the run
// exits 0 with them recorded. It exits 1 only when the comparison itself is
// untrustworthy: a failed direction probe, or a harness error.
//
// # THE DIRECTION MAPPING
//
// The two APIs take their arguments in opposite orders AND opposite senses:
//
//	warden:  core.Subsumes(derived, parent) bool          // true == permitted
//	tenuo:   parent.validate_attenuation(&derived) -> Result<()>  // Ok == permitted
//
// warden's FIRST argument is tenuo's ARGUMENT; warden's SECOND argument is
// tenuo's RECEIVER. Getting this backwards silently inverts every asymmetric
// rule while leaving the symmetric ones (wildcard/wildcard, exact/exact)
// agreeing, so the mistake would look like a partial success. The
// direction-probe category exists to make that impossible: each probe case has
// a swapped twin whose verdict must differ, and the run aborts before any
// comparison is reported if a probe comes back wrong on either side.
//
// Run:  go run ./interop        (needs cargo; builds interop/shim on first run)
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"github.com/igorkg/warden/internal/core"
)

type shimResult struct {
	ID      string `json:"id"`
	Verdict string `json:"verdict"` // permit | deny | unsupported
	Detail  string `json:"detail"`
}

type row struct {
	Case
	Warden string // permit | deny | unsupported
	Tenuo  string
}

func (r row) agrees() bool { return r.Warden == r.Tenuo }

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "interop: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	cases := corpus()

	tenuo, err := runShim(cases)
	if err != nil {
		return err
	}

	rows := make([]row, 0, len(cases))
	for _, c := range cases {
		tv, ok := tenuo[c.ID]
		if !ok {
			return fmt.Errorf("shim returned no verdict for case %q", c.ID)
		}
		rows = append(rows, row{Case: c, Warden: wardenVerdict(c), Tenuo: tv})
	}

	if err := gate(rows); err != nil {
		return err
	}

	report := render(rows)
	out := filepath.Join("interop", "results", "verdicts.md")
	if err := os.MkdirAll(filepath.Dir(out), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(out, []byte(report), 0o644); err != nil {
		return err
	}
	fmt.Print(report)
	fmt.Fprintf(os.Stderr, "\nwritten: %s\n", out)
	return nil
}

// wardenVerdict parses both sides with warden's own parser, so a constraint
// warden rejects at parse time is reported as unsupported rather than silently
// becoming a deny — the same distinction the shim draws.
func wardenVerdict(c Case) string {
	p, err := core.ParseConstraint(c.Parent)
	if err != nil {
		return "unsupported"
	}
	d, err := core.ParseConstraint(c.Derived)
	if err != nil {
		return "unsupported"
	}
	if core.Subsumes(d, p) {
		return "permit"
	}
	return "deny"
}

func runShim(cases []Case) (map[string]string, error) {
	in, err := json.Marshal(cases)
	if err != nil {
		return nil, err
	}
	cmd := exec.Command("cargo", "run", "--quiet",
		"--manifest-path", filepath.Join("interop", "shim", "Cargo.toml"))
	cmd.Stdin = bytes.NewReader(in)
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("running shim: %w", err)
	}
	var results []shimResult
	if err := json.Unmarshal(out, &results); err != nil {
		return nil, fmt.Errorf("decoding shim output: %w", err)
	}
	m := make(map[string]string, len(results))
	for _, r := range results {
		m[r.ID] = r.Verdict
	}
	return m, nil
}

// gate aborts the whole run if the argument mapping is not what the comment
// above claims. Nothing downstream is trustworthy if this fails.
func gate(rows []row) error {
	var bad []string
	for _, r := range rows {
		if r.Category != catProbe || r.Want == nil {
			continue
		}
		want := "deny"
		if *r.Want {
			want = "permit"
		}
		if r.Warden != want {
			bad = append(bad, fmt.Sprintf("%s: warden=%s want=%s", r.ID, r.Warden, want))
		}
		if r.Tenuo != want {
			bad = append(bad, fmt.Sprintf("%s: tenuo=%s want=%s", r.ID, r.Tenuo, want))
		}
	}
	if len(bad) > 0 {
		return fmt.Errorf("direction probe failed, comparison is void:\n  %s",
			strings.Join(bad, "\n  "))
	}
	return nil
}

func render(rows []row) string {
	byCat := map[string][]row{}
	for _, r := range rows {
		byCat[r.Category] = append(byCat[r.Category], r)
	}

	var b strings.Builder
	b.WriteString("# §4.5 subsumption: warden vs tenuo\n\n")
	b.WriteString("Generated by `go run ./interop`. Measurement, not a test: a disagreement\n")
	b.WriteString("is a finding, not a failure. Verdicts are (parent, derived) pairs;\n")
	b.WriteString("`permit` means the derived constraint is a valid attenuation of the parent.\n\n")

	agree, disagree := 0, 0
	for _, r := range rows {
		if r.agrees() {
			agree++
		} else {
			disagree++
		}
	}
	fmt.Fprintf(&b, "%d cases: %d agree, %d disagree.\n\n", len(rows), agree, disagree)

	b.WriteString("| category | cases | agree | disagree |\n|---|---:|---:|---:|\n")
	for _, cat := range categoryOrder {
		a, d := 0, 0
		for _, r := range byCat[cat] {
			if r.agrees() {
				a++
			} else {
				d++
			}
		}
		fmt.Fprintf(&b, "| %s | %d | %d | %d |\n", cat, len(byCat[cat]), a, d)
	}
	b.WriteString("\n")

	for _, cat := range categoryOrder {
		rs := byCat[cat]
		if len(rs) == 0 {
			continue
		}
		sort.SliceStable(rs, func(i, j int) bool { return !rs[i].agrees() && rs[j].agrees() })
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", cat, categoryWhy[cat])
		b.WriteString("| case | warden | tenuo | | why this pair is here |\n|---|---|---|---|---|\n")
		for _, r := range rs {
			mark := ""
			if !r.agrees() {
				mark = "**DIFFERS**"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s |\n", r.ID, r.Warden, r.Tenuo, mark, r.Why)
		}
		if n := categoryNote[cat]; n != "" {
			fmt.Fprintf(&b, "%s\n", n)
		}
		b.WriteString("\n")
	}
	return b.String()
}
